[package]
name = "rfv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
console = "0.15.7"
fhe = { path = "./fhe.rs/crates/fhe" }
fhe-traits = { path = "./fhe.rs/crates/fhe-traits" }
fhe-util = { path = "./fhe.rs/crates/fhe-util" }
# fhe = { git = "https://github.com/gnosisguild/fhe.rs", version = "0.1.0-beta.7" }
# fhe-traits = { git = "https://github.com/gnosisguild/fhe.rs", version = "0.1.0-beta.7" }
# fhe-util = { git = "https://github.com/gnosisguild/fhe.rs", version = "0.1.0-beta.7" }
rand_chacha = "0.3.1"
rand = "0.8.5"
ethers = "2.0"
getrandom = { version = "0.2.11", features = ["js"] }
# Ethers' async features rely upon the Tokio async runtime.
tokio = { version = "1", features = ["full"] }
bincode = "1.0"
hyper = { version = "1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
iron = "0.4.0"
rustc-serialize = "0.3"
router = "0.4.0"
walkdir = "2.5.0"
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/bin/web_test.rs"

